#!/bin/bash

IDENTIFIER=MYSQL-TILE

source ../common || die "ERROR: 'common' not found"
source ../common-backup || die "ERROR: 'common-backup' not found"
source ../config/environment.sh || die "ERROR: configuration file 'environment.sh' not found"

# Change the Name of the Output tar archive to include tile name
set_tile_identifier() {
	export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME
}

validate_connection() {
	for host in $MYSQL_HOSTS; do
		nc -w1 -z $host 3306
		if [ $? -ne 0 ]; then
			die "CONNECTION ERROR ON HOST: $host PORT: 3306"
		fi
	done
}

prepare_backup() {
	out "Preparing Backup"
	local ret=0
	mkdir -p "$WORK_DIR" || ret=1
	mkdir -p "$DEPLOYMENT_DIR" || ret=1
	mkdir -p "$DATABASE_DIR" || ret=1
	if [ $ret -eq 0 ]; then
		out "Preparations DONE"
	else
		die "ERROR: Preparations FAILED"
	fi
}

cleanup_backup() {
	rm -r $WORK_DIR
}

# Loop through the hosts so that in case one is failing, the other one is used.
export_mysqldb() {
	for host in $MYSQL_HOSTS; do
		mysqldump -u $MYSQL_USER -p$MYSQL_PASS -h $host --all-databases > $DATABASE_DIR/all_databases.sql
		mysqldump -u $MYSQL_USER -p$MYSQL_PASS -h $host mysql_broker > $DATABASE_DIR/mysql_broker.sql
		if [ $? -eq 0 ]; then
			break
		else
			continue
		fi
	done
	validate_mysqldump $DATABASE_DIR/all_databases.sql
	validate_mysqldump $DATABASE_DIR/mysql_broker.sql
}

validate_mysqldump() {
	DUMPFILE=$1
	if [ -f $DUMPFILE ]; then
		if [ -n "`tail -n 40 $DUMPFILE | grep 'Dump completed on'`" ]; then
			out "BACKUP FOR $(basename $DUMPFILE) SUCCESSFULLY"
		else
			die "BACKUP FOR $(basename $DUMPFILE) FAILED"
		fi
	fi
}

set_tile_identifier
login_opsman
prepare_backup
export_installation_settings
fetch_mysql_credentials
validate_connection
export_mysqldb
zip_all_together
logout_all
