#!/bin/bash

cd ..
SCRIPT_BASE=$(pwd)
IDENTIFIER=MYSQL-TILE

source common || die "$IDENTIFIER: ERROR: 'common' not found"
source common-backup || die "$IDENTIFIER: ERROR: 'common-backup' not found"
source config/environment.sh || die "$IDENTIFIER: ERROR: configuration file 'environment.sh' not found"

# Change the Name of the Output tar archive to include tile name
set_tile_identifier() {
	eval "$(sed "s#^export BACKUP_DIR_NAME=.*#export BACKUP_DIR_NAME=$IDENTIFIER-$BACKUP_DIR_NAME#" config/environment.sh)"
}

validate_connection() {
	out "$IDENTIFIER: Validating connection"
	for host in $MYSQL_HOSTS; do
		nc -w1 -z $host 3306
		if [ $? -ne 0 ]; then
			die "$IDENTIFIER: ERROR: Connection to host: $host port: 3306 FAILED"
		fi
	done
	out "$IDENTIFIER: Connection test SUCCESSFUL"
}

prepare_backup() {
	out "$IDENTIFIER: Preparing Backup"
	local ret=0
	mkdir -p "$WORK_DIR" || ret=1
	mkdir -p "$DEPLOYMENT_DIR" || ret=1
	mkdir -p "$DATABASE_DIR" || ret=1
	if [ $ret -eq 0 ]; then
		out "$IDENTIFIER: Preparations DONE"
	else
		die "$IDENTIFIER: ERROR: Preparations FAILED"
	fi
}

cleanup_backup() {
	rm -r $WORK_DIR
}

# Loop through the hosts so that in case one is failing, the other one is used.
export_mysqldb() {
	out "$IDENTIFIER: Dumping databases"
	for host in $MYSQL_HOSTS; do
		mysqldump -u $MYSQL_USER -p$MYSQL_PASS -h $host --all-databases > $DATABASE_DIR/all_databases.sql
		mysqldump -u $MYSQL_USER -p$MYSQL_PASS -h $host mysql_broker > $DATABASE_DIR/mysql_broker.sql
		if [ $? -eq 0 ]; then
			break
		else
			continue
		fi
	done
	validate_mysqldump $DATABASE_DIR/all_databases.sql
	validate_mysqldump $DATABASE_DIR/mysql_broker.sql
	out "$IDENTIFIER: Dump SUCCESSFUL"
}

validate_mysqldump() {
	DUMPFILE=$1
	out "$IDENTIFIER: Validating dump '$(basename $DUMPFILE)'"
	if [ -f $DUMPFILE ]; then
		if [ -n "`tail -n 40 $DUMPFILE | grep 'Dump completed on'`" ]; then
			out "$IDENTIFIER: Validation of '$(basename $DUMPFILE)' SUCCESSFUL"
		else
			die "$IDENTIFIER: Validation of '$(basename $DUMPFILE)' FAILED"
		fi
	fi
}

set_tile_identifier
login_opsman
prepare_backup
export_installation_settings
fetch_mysql_credentials
validate_connection
export_mysqldb
zip_all_together
logout_all

out "$IDENTIFIER: Backup DONE"
