#!/bin/bash --login

. common
. backup_director.sh

out() {
	echo "$(date) $SCRIPTNAME[$$]: ${1+$@}" 1>&2
}

require_binary() {
	local bin="$1"
	if [ -z "$bin" ]; then
		out "Warning: 'require' not used properly. Please specify an argument."
		return 0
	fi

	local filepath=$(which "$bin" 2>/dev/null)
	if [ -z "$filepath" ]; then
		out "$1 not installed"
		return 1
	fi
}

validate_software() {
	out "Validate Mandatory Tools"
	local ret=0
	require_binary bosh || ret=1
	require_binary curl || ret=1
	require_binary expect || ret=1
	require_binary mysqldump || ret=1
	require_binary pg_dump || ret=1
	require_binary rsync || ret=1
	require_binary ruby || ret=1
	require_binary uaac || ret=1
	if [ $ret -eq 0 ]; then
		out "Validations DONE"
	else
		out "ERROR: Validations FAILED"
		exit 1
	fi
}

verify_deployment_backedUp() {
	out "VERIFY CF DEPLOYMENT MANIFEST"
	export CF_DEPLOYMENT_NAME=`bosh deployments | grep "cf-" | cut -d '|' -f 2 | tr -s ' ' | grep "cf-" | tr -d ' ' | head -1`
	export CF_DEPLOYMENT_FILE_NAME=$CF_DEPLOYMENT_NAME.yml

	out "FILES LOOKING FOR $CF_DEPLOYMENT_NAME $CF_DEPLOYMENT_FILE_NAME"

	if [ -f $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME ]; then
		out "file exists"
	else
		out "file does not exist"
		bosh download manifest $CF_DEPLOYMENT_NAME $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME
	fi
}

export_Encryption_key() {
	out "EXPORT DB ENCRYPTION KEY"
	grep -E 'db_encryption_key' $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME | cut -d ':' -f 2 | sort -u > $WORK_DIR/cc_db_encryption_key.txt
}

bosh_status() {
	out "EXECUTE BOSH STATUS"
	bosh status > $WORK_DIR/bosh_status.txt
	export BOSH_UUID=`grep UUID $WORK_DIR/bosh_status.txt | cut -d 'D' -f 2 | tr -d ' ' | sort -u`

	export UUID_EXISTS=`grep -Fxq $BOSH_UUID $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME`
	if [[ -z $UUID_EXISTS ]]; then
		out "UUID Matches"
	else
		out "UUID Mismatch"
		exit 1
	fi

	rm -rf $WORK_DIR/bosh_status.txt
}

set_bosh_deployment() {
	out "SET THE BOSH DEPLOYMENT"
	bosh deployment $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME
}

export_bosh_vms() {
	out "EXPORT BOSH VMS"
	OUTPUT=`bosh vms | grep "cloud_controller[-/]" | awk '{print $2}'`
	echo $OUTPUT > $WORK_DIR/bosh-vms.txt
}

stop_cloud_controller() {
	out "STOPPING CLOUD CONTROLLER"
	OUTPUT=`cat $WORK_DIR/bosh-vms.txt`

	for word in $OUTPUT; do
		JOB=`echo $word | cut -d '/' -f 1`
		INDEX=`echo $word | cut -d '/' -f 2`

		bosh -n stop $JOB $INDEX --force
	done
}

export_cc_db() {
	out "EXPORT CCDB"
	export_db cf ccdb admin 2544 "ccdb" $DATABASE_DIR/ccdb.sql
}

export_uaadb() {
	out "EXPORT UAA-DB"
	export_db cf uaadb root 2544 "uaa" $DATABASE_DIR/uaadb.sql
}

export_consoledb() {
	out "EXPORT CONSOLE-DB"
	export_db cf consoledb root 2544 "console" $DATABASE_DIR/console.sql
}

export_db() {
	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml $1 $2 $3`

	local USERNAME=`echo $output | cut -d '|' -f 1`
	local PGPASSWORD=`echo $output | cut -d '|' -f 2`
	local IPS=`echo $output | cut -d '|' -f 3`
	local PORT=$4
	local DB=$5
	local DB_FILE=$6

	if [ -n "$IPS" ]; then
		for IP in $IPS; do
			out "Export PostgreSQL $DB from $IP"

			pg_dump -h $IP -U $USERNAME -p $PORT -c $DB > $DB_FILE
			if [ $? -eq 0 ]; then
				break
			else
				out "ERROR: An error occurred dumping the databases from server $IP"
			fi
		done
	else
		out "Info: no VM instances found for $DB"
	fi
}

export_nfs_server() {
	out "EXPORT NFS-SERVER"

	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml cf nfs_server vcap`

	export NFS_SERVER_USER=`echo $output | cut -d '|' -f 1`
	export NFS_SERVER_PASSWORD=`echo $output | cut -d '|' -f 2`
	export NFS_IP=`echo $output | cut -d '|' -f 3`

	ssh-keygen -R $NFS_IP

	/usr/bin/expect -c "
		set timeout -1

		spawn scp -rp $NFS_SERVER_USER@$NFS_IP:/var/vcap/store/shared $NFS_DIR

		expect {
			-re ".*Are.*.*yes.*no.*" {
				send yes\r ;
				exp_continue
			}

			"*?assword:*" {
				send $NFS_SERVER_PASSWORD\r
			}
		}
		expect {
			"*?assword:*" {
				send $NFS_SERVER_PASSWORD\r
				interact
			}
		}

		exit
	"
}

start_cloud_controller() {
	out "STARTING CLOUD CONTROLLER"
	OUTPUT=`cat $WORK_DIR/bosh-vms.txt`

	for word in $OUTPUT
	do
		JOB=`echo $word | cut -d '/' -f 1`
		INDEX=`echo $word | cut -d '/' -f 2`

		bosh -n start $JOB $INDEX --force
	done
}

export_mysqldb() {
	output=`ruby lib/installationparser/app.rb $WORK_DIR/installation.yml cf mysql root mysql_proxy`

	export USERNAME=`echo $output | cut -d '|' -f 1`
	export PASSWORD=`echo $output | cut -d '|' -f 2`
	export IPS=`echo $output | cut -d '|' -f 3 | tr ',' ' '`

	DB_FILE=$DATABASE_DIR/mysql.sql

	for IP in $IPS; do
		out "EXPORT MySQL DB from $IP"

		mysqldump -u $USERNAME -p"$PASSWORD" -h $IP --all-databases > $DB_FILE
		if [ $? -eq 0 ]; then
			break
		else
			out "ERROR: An error occurred dumping the databases from server $IP"
		fi
	done
}

export_installation() {
	if [[ "Y" = "$COMPLETE_BACKUP" || "y" = "$COMPLETE_BACKUP" ]]; then
		CONNECTION_URL=https://$OPS_MANAGER_HOST/api/installation_asset_collection

		out "EXPORT INSTALLATION FILES FROM " $CONNECTION_URL
		export UAA_ACCESS_TOKEN=`cat ~/.uaac.yml | grep "access_token:" | cut -d':' -f2 | cut -d' ' -f2`
		curl "$CONNECTION_URL" -X GET -k -H "Authorization: Bearer $UAA_ACCESS_TOKEN" -o $WORK_DIR/installation.zip
	fi
}

zip_all_together() {
	cd $WORK_DIR
	cd ..
	cmd=`tar -zcvf $BACKUP_DIR_NAME.tar.gz $BACKUP_DIR_NAME`
	out "Compressed the backup into $BACKUP_DIR_NAME.tar.gz"
	cmd=`rm -rf $WORK_DIR`
}

makedir() {
	mkdir -p "$1"
	local ret=$?
	if [ $ret -ne 0 ]; then
		out "ERROR: Can't create directory '$1'"
	fi
	return $ret
}

prepare() {
	out "Preparing Backup"
	local ret=0
	makedir $WORK_DIR || ret=1
	makedir $NFS_DIR || ret=1
	makedir $DEPLOYMENT_DIR || ret=1
	makedir $DATABASE_DIR || ret=1
	if [ $ret -eq 0 ]; then
		out "Preparations DONE"
	else
		out "ERROR: Preparations FAILED"
		exit 1
	fi
}

execute() {
	prepare
	validate_software

	scp_files /var/tempest/workspaces/default/deployments/*.yml $DEPLOYMENT_DIR
	scp_files /var/tempest/workspaces/default/root_ca_certificate $WORK_DIR

	export CA_CERT_LOCATION=$WORK_DIR/root_ca_certificate

	login_opsman
	export_installation_settings
	fetch_bosh_connection_parameters
	bosh_login
	verify_deployment_backedUp
	export_Encryption_key
	bosh_status
	set_bosh_deployment
	export_bosh_vms

	# Backported from v1.6 version in case databases were not migrated.
	# Only new PCF 1.7 installs are using MySQL only.
	export_cc_db
	export_uaadb
	export_consoledb

	# stop_cloud_controller
	export_nfs_server
	export_mysqldb
	# start_cloud_controller
	export_installation
	export_p_bosh

	zip_all_together
	logout_all
}

if [[ ! -f "config/environment.sh" ]]; then

	if [ $# -lt 6 ]; then
		echo "Usage: ./backup_with_om <OPS MGR HOST or IP> <SSH USER> <SSH PASSWORD> <OPS MGR ADMIN USER> <OPS MGR ADMIN PASSWORD> <OUTPUT DIR> <COMPLETE BACKUP>"
		printf "\t %s \t\t\t %s \n" "OPS MGR HOST or IP:" "OPS Manager Host or IP"
		printf "\t %s \t\t\t\t %s \n" "SSH USER:" "OPS Manager SSH Username"
		printf "\t %s \t\t\t\t %s \n" "SSH PASSWORD:" "OPS Manager SSH Password"
		printf "\t %s \t\t\t %s \n" "OPS MGR ADMIN USER:" "OPS Manager Admin Username"
		printf "\t %s \t\t %s \n" "OPS MGR ADMIN PASSWORD:" "OPS Manager Admin Password"
		printf "\t %s \t\t\t\t %s \n" "OUTPUT DIR:" "Backup Directory"
		printf "\t %s \t\t\t %s \n" "COMPLETE BACKUP:" "Specify 'Y' for complete backup"
		exit 1
	fi

	export DATE=`date +%Y_%m_%d`
	export OPS_MANAGER_HOST=$1
	export SSH_USER=$2
	export OPS_MGR_SSH_PASSWORD=$3
	export OPS_MGR_ADMIN_USERNAME=$4
	export OPS_MGR_ADMIN_PASSWORD=$5
	export BACKUP_DIR_NAME=Backup_$DATE
	export WORK_DIR=$6/$BACKUP_DIR_NAME
	export NFS_DIR=$WORK_DIR/nfs_share
	export DEPLOYMENT_DIR=$WORK_DIR/deployments
	export DATABASE_DIR=$WORK_DIR/database

	export COMPLETE_BACKUP=$7

else
	source "config/environment.sh"
fi

execute

out "BACKUP SUCCESSFUL"
